version: 2

sources:
  - name: dev
    schema: demo
    database: dev
    tables:
      - name: orders
        meta: 
          dagster:
            asset_key: ["soda_UI_check",]
      - name: order_items
        meta: 
          dagster:
            asset_key: ["load_from_s3",]
      # - name: products
      #   meta: 
      #     dagster:
      #       asset_key: ["soda_UI_check"]
